### ISSUE TITLE
WhatsApp or Telegram

### ISSUE THREAD

**Issue by bodasooqa** [yongava/fundpagev2#14]
Maybe Telegram?

**Comment by bodasooqa** [comment]
<img width="547" alt="Снимок экрана 2020-11-12 в 19 45 48" src="https://user-images.githubusercontent.com/34233108/98969216-ace78500-251f-11eb-8341-e7262958652a.png">
It is better not to write this on upwork, otherwise you will be banned

**Comment by yongava** [comment]
my telegram +66962823669
